feat(snap): add content interface for device configuration
canonical/edgex-device-rest-go pull request #2
Opened 2021-05-05 15:18 UTC by siggiskulason

The device-config slot allows another snap to seed this device snap with initial configuration
and device profiles. To use, create a new snap with the following in snapcraft.yaml:

```
plugs:
  device-config:
    interface: content
    content: device-config
    target: $SNAP_DATA/device-rest-configuration
```

It is then possible to connect the plug and slot with

```
sudo snap connect your-snap:device-config edgex-device-rest:device-config
```

and your test snap can then copy the configuration files by doing

```
cp $SNAP/filetocopy.yaml $SNAP_DATA/device-rest/configuration/

```

Signed-off-by: Siggi Skulason <siggi.skulason@canonical.com>

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/device-rest-go/blob/master/.github/CONTRIBUTING.md

## What is the current behavior?

## Issue Number:

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## New Imports

- [ ] Yes
- [ ] No

## Specific Instructions

## Other information

2021-05-05 15:28 UTC, tonyespy requested changes
Can you please add the documentation that you included in your PR description to the snap/README file?

Also curious why the device service implements a slot vs. a plug? As typically a snap providing content implements the slot. We did this for the vault token interface because it allowed the consuming snap to name the directories that get created under `/secrets`, and maybe the same applied to the app-service-config profiles content interface?

2021-05-05 15:36 UTC, siggiskulason commented
Thanks for the comments, @tonyespy ,

> Can you please add the documentation that you included in your PR description to the snap/README file?
Will do!

> Also curious why the device service implements a slot vs. a plug? As typically a snap providing content implements the slot. We did this for the vault token interface because it allowed the consuming snap to name the directories that get created under `/secrets`, and maybe the same applied to the app-service-config profiles content interface?

Only reason was that it was what we did when adding this earlier to the LLRP snap - see [this commit](https://github.com/canonical/edgex-device-rfid-llrp-go/pull/1/commits/6dee5eea0e8145c161e907bb2b476c3579397961). I think that may have been because it was what we did for the ASC interface - which, as you said, was to handle the requirements of setting up secrets for Vault. I'll change this around and make it into a plug - and also modify the LLRP implementation in a separate PR.

2021-05-06 00:07 UTC, tonyespy requested changes
LGTM, however some minor changes requested for snap/README.

2021-05-06 00:07 UTC, tonyespy commented on snap/README.md
> +    read: $SNAP_DATA/device-profiles
The only thing I'd change is the name of the `read` directory, as device-profiles is a bit of an overloaded term. I'd suggest just using "config" here.

2021-05-06 00:07 UTC, tonyespy commented on snap/README.md
> +snap with initial configuration and device profiles. To use, create a new
Maybe add a little bit more here to explain that the other snap can provide both a configuration file and one or more device profiles. It's not totally obvious that's possible...

2021-05-06 11:39 UTC, siggiskulason commented on snap/README.md
> +    read: $SNAP_DATA/device-profiles
changed to "config"

2021-05-06 11:39 UTC, siggiskulason commented on snap/README.md
> +snap with initial configuration and device profiles. To use, create a new
Good point - I added some more information..

2021-05-06 17:02 UTC, tonyespy approved these changes
LGTM

2021-05-06 17:02 UTC, merged